import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface AuroraBackgroundProps {
  children: React.ReactNode; // Adjust this according to your actual usage
  // Add other props as needed
}

const AuroraBackground: React.FC<AuroraBackgroundProps> = ({ children }) => {
  // Your component logic here
  return (
    // JSX for your component
    <div className="aurora-background">
      {/* Render children if needed */}
      {children}
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <div className="w-full relative flex items-center justify-center">
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
